gpt:
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions
    user-base-score: 10


spring:
  profiles.active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  file:
    upload-dir: ./data/uploads/files
logging:
  file:
    path: ./data/logs
  level:
    root: ERROR
    org:
      smartjobs: INFO
  org:
    springframework:
      boot:
        test:
          context:
            springboottestcontextbootstrapper: error
      context:
        support:
          abstractcontextloader: off
          annotationconfigcontextloaderutils: off
        thymeleaf: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "|>|%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

threads:
  virtual:
    enabled: true

thymeleaf:
  mode: HTML
  encoding: UTF-8
  prefix: classpath:/templates/
  suffix: .html

web:
  resources:
    static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
