spring:
  config:
    import: optional:file:prod.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Nowomannocry

site:
  domain: www.smartjobs.site
  email: mailtrap@smartjobs.site

mail:
  smtp:
    host: live.smtp.mailtrap.io
    port: 587
    username: api
    password: ${EMAIL_PASSWORD}
