spring:
  resources:
    chain:
      strategy:
        content:
          enabled: true
          cache:
            time-to-live: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: cream
  thymeleaf:
    cache: false

logging:
  file:
    path: ./data/logs
  level:
    root: ERROR
    org:
      smartjobs:
        com: DEBUG
