server:
  port: 8443

spring:
  config:
    import: optional:file:dev.env[.properties]
  resources:
    chain:
      strategy:
        content:
          enabled: true
          cache:
            time-to-live: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${DATABASE_PASSWORD}
  thymeleaf:
    cache: false

logging:
  file:
    path: ./data/logs
  level:
    root: ERROR
    org:
      smartjobs: TRACE
  org:
    springframework:
      boot:
        test:
          context:
            springboottestcontextbootstrapper: ERROR
      context:
        support:
          abstractcontextloader: off
          annotationconfigcontextloaderutils: off
        thymeleaf: DEBUG

mail:
  smtp:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 1d25b729c23ddf
    password: ${EMAIL_PASSWORD}
