spring:
  config:
    import: optional:file:prod.env[.properties]
  datasource:
    url: jdbc:postgresql://secretsauce.cxs4y0ae6u93.eu-west-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: CreamyThresh

site:
  domain: www.smartjobs.site
  email: mailtrap@smartjobs.site

mail:
  smtp:
    host: live.smtp.mailtrap.io
    port: 587
    username: api
    password: ${EMAIL_PASSWORD}
