server:
  port: 8080 # HTTP port
  ssl:
    enabled: false # SSL disabled for dev

spring:
  config:
    import: optional:file:dev.env[.properties]
  resources:
    chain:
      strategy:
        content:
          enabled: true
          cache:
            time-to-live: 0
  datasource:
    url: jdbc:h2:mem:smartjobsdb_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Use 'update' or 'create-drop' for H2 dev
  flyway:
    enabled: false # Disable Flyway for H2 dev if not configured for it
  thymeleaf:
    cache: false

logging:
  file:
    path: ./data/logs
  level:
    root: ERROR
    org:
      smartjobs: TRACE
  org:
    springframework:
      boot:
        test:
          context:
            springboottestcontextbootstrapper: ERROR
      context:
        support:
          abstractcontextloader: off
          annotationconfigcontextloaderutils: off
        thymeleaf: DEBUG
